# Generated by Django 5.0.7 on 2024-07-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('years_of_experience', models.IntegerField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('salary', models.IntegerField()),
                ('hire_date', models.DateField()),
                ('bio', models.TextField()),
                ('courses', models.ManyToManyField(related_name='teachers', to='courses.course')),
            ],
        ),
    ]
